import { requireGuildAccess } from '@/lib/guards';
import { mediaConfigurationError, mediaSettings } from '@/lib/media-data';
import { voiceResources } from '@/lib/voice-data';
import { ActionForm } from '@/app/components/action-form';
import { Button, Checkbox, Input, Switch } from '@/app/components/controls';
import { Select } from '@/app/components/select';
import { ResourceMultiSelect } from '@/app/components/resource-multiselect';
import { saveMediaSettings } from '../actions';
const policyLabels = { addTracks: 'Додавати треки', pauseResume: 'Пауза та відновлення', skip: 'Прямий пропуск треку', removeOwnTracks: 'Видаляти власні треки', removeAnyTracks: 'Видаляти будь-які треки', reorderOwnTracks: 'Переміщувати власні треки', reorderQueue: 'Змінювати всю чергу', changeVolume: 'Змінювати гучність', stopSession: 'Зупиняти сесію' };
export default async function MediaSettingsPage({ params }: { params: Promise<{ guildId: string }> }) {
  const { guildId } = await params; const access = await requireGuildAccess(guildId, 'media.view'); const [settings, resources] = await Promise.all([mediaSettings(guildId), voiceResources(guildId, access.guild.resourceRevision)]);
  const canManage = access.permissions.has('media.manage'); const configurationError = mediaConfigurationError(); const editable = canManage && !configurationError;
  const voices = resources.channels.filter((channel) => channel.type === 2).map((channel) => ({ id: channel.id, name: channel.name ?? channel.id })); const roles = resources.roles.filter((role) => role.id !== guildId);
  return <section className="settings-page"><h2>Налаштування Медіа</h2>{!canManage && <p className="form-feedback">Лише перегляд. Зміни потребують media.manage.</p>}{canManage && configurationError && <p className="form-feedback" role="status">{configurationError}</p>}<ActionForm action={saveMediaSettings.bind(null, guildId)} feedbackPlacement="toast" className="voice-form settings-form settings-sections media-settings-form">
    <fieldset className="settings-card settings-section"><legend>Основне</legend><Switch name="enabled" label="Увімкнути Медіа" help="Вимкнення зупиняє аудіо й зберігає чергу." defaultChecked={settings.enabled} disabled={!editable} /><Switch name="allowLiveStreams" label="Дозволити прямі трансляції" help="Публічні трансляції підтримуваних джерел. Для аудіофайлів діє ліміт тривалості." defaultChecked={settings.allowLiveStreams} disabled={!editable} /></fieldset>
    <fieldset className="settings-card settings-section"><legend>Керування</legend><div className="form-grid"><label>Режим<Select name="controlMode" aria-label="Режим керування" defaultValue={settings.controlMode} disabled={!editable}><option value="OPEN">Відкрите керування</option><option value="QUEUE">Черга та дозволені дії</option><option value="DJ">DJ керує, учасники замовляють</option></Select></label><label>Пропуск<Select name="skipMode" aria-label="Режим пропуску" defaultValue={settings.skipMode} disabled={!editable}><option value="direct">Прямий, якщо дозволено політикою</option><option value="vote">Голосування</option><option value="djOnly">Лише DJ</option></Select></label><label>Частка голосів<Input type="number" name="skipVoteRatio" min="0.1" max="1" step="0.05" defaultValue={settings.skipVoteRatio} disabled={!editable} /><small>0.5 = 50%. Усі люди у Voice, включно з оглушеними; боти не рахуються.</small></label></div><Switch name="allowRemoteAdminControl" label="Віддалене керування адміністратора" help="Лише media.manage може керувати з іншого Voice. DJ має бути у Voice SCRT." defaultChecked={settings.allowRemoteAdminControl} disabled={!editable} /><Switch name="allowRemoteRequests" label="Дозволити віддалені замовлення" defaultChecked={settings.allowRemoteRequests} disabled={!editable} /><ResourceMultiSelect name="djRoleIds" label="DJ ролі" options={roles} defaultSelected={settings.djRoleIds} disabled={!editable} /><div className="form-grid">{Object.entries(policyLabels).map(([key, label]) => <Checkbox key={key} name={`policy.${key}`} label={label} defaultChecked={settings.sameVoiceUsersCan[key as keyof typeof policyLabels]} disabled={!editable} />)}</div><p className="field-help">Ці дії доступні звичайним учасникам лише у Voice SCRT. media.control або DJ роль дають ширше керування. Блокування сесії має пріоритет.</p></fieldset>
    <fieldset className="settings-card settings-section"><legend>Черга</legend><div className="form-grid"><label>Порядок<Select name="queueMode" aria-label="Порядок черги" defaultValue={settings.queueMode} disabled={!editable}><option value="normal">FIFO</option><option value="fair">Справедлива: по черзі між учасниками</option></Select></label><label>Дублікати<Select name="duplicatePolicy" aria-label="Дублікати" defaultValue={settings.duplicatePolicy} disabled={!editable}><option value="allow">Дозволити, без повторів від одного учасника</option><option value="reject">Відхиляти</option><option value="move_existing">Перемістити наявний трек</option></Select></label><label>Максимум у черзі<Input type="number" name="maxQueueItems" min="1" max="100" defaultValue={settings.maxQueueItems} disabled={!editable} /></label><label>Треків на учасника<Input type="number" name="maxTracksPerUser" min="1" max="100" defaultValue={settings.maxTracksPerUser} disabled={!editable} /></label><label>Максимальна тривалість, секунди<Input type="number" name="maxTrackDurationSeconds" min="30" max="10800" defaultValue={settings.maxTrackDurationSeconds} disabled={!editable} /></label></div><p className="field-help">Аудіофайли з невідомою тривалістю завершуються після цього ліміту. Справедливий порядок застосовується до збереженої черги без втрати її метаданих.</p></fieldset>
    <fieldset className="settings-card settings-section"><legend>Voice</legend><ResourceMultiSelect name="allowedVoiceChannelIds" label="Дозволені канали" options={voices} defaultSelected={settings.allowedVoiceChannelIds} disabled={!editable} /><ResourceMultiSelect name="allowedCategoryIds" label="Дозволені категорії" options={resources.channels.filter((channel) => channel.type === 4).map((channel) => ({ id: channel.id, name: channel.name ?? channel.id }))} defaultSelected={settings.allowedCategoryIds} disabled={!editable} /><ResourceMultiSelect name="blockedVoiceChannelIds" label="Заблоковані канали" options={voices} defaultSelected={settings.blockedVoiceChannelIds} disabled={!editable} /><p className="field-help">Порожні списки дозволяють усі звичайні Voice, крім AFK і заблокованих. Категорії охоплюють нові тимчасові кімнати.</p><div className="form-grid"><label>Порожній канал<Select name="emptyVoiceBehavior" aria-label="Порожній канал" defaultValue={settings.emptyVoiceBehavior} disabled={!editable}><option value="pause_then_leave">Пауза, потім вихід</option><option value="stop_then_leave">Зупинка, потім вихід</option></Select></label><label>Час на повернення, секунди<Input type="number" name="emptyVoiceGraceSeconds" min="5" max="3600" defaultValue={settings.emptyVoiceGraceSeconds} disabled={!editable} /></label></div><Switch name="resumeOnRejoin" label="Відновлювати після повернення слухача" help="За замовчуванням потрібне явне відновлення." defaultChecked={settings.resumeOnRejoin} disabled={!editable} /></fieldset>
    <fieldset className="settings-card settings-section"><legend>Відтворення та історія</legend><div className="form-grid"><label>Гучність нової сесії<Input type="number" name="defaultVolume" min="0" max="100" defaultValue={settings.defaultVolume} disabled={!editable} /></label><label>Максимальна гучність<Input type="number" name="maxVolume" min="1" max="100" defaultValue={settings.maxVolume} disabled={!editable} /></label><label>Зберігати історію, днів<Input type="number" name="historyRetentionDays" min="1" max="90" defaultValue={settings.historyRetentionDays} disabled={!editable} /></label><label>Explicit контент<Select name="explicitPolicy" aria-label="Explicit контент" defaultValue={settings.explicitPolicy} disabled={!editable}><option value="allow">Дозволяти</option><option value="warn">Показувати позначку</option><option value="block">Блокувати відомий explicit</option></Select><small>Якщо джерело не надає позначки, статус невідомий.</small></label></div></fieldset>
    <fieldset className="settings-card settings-section"><legend>Автоматичне відключення</legend><label>Час без музики, секунди<Input type="number" name="inactivityDisconnectSeconds" min="0" max="3600" step="1" defaultValue={settings.inactivityDisconnectSeconds} disabled={!editable} /><small>За замовчуванням 300 секунд (5 хвилин). 0 — вимкнути; максимум 3600 секунд (1 година).</small></label><p className="field-help">Бот вийде з голосового каналу після цього часу на паузі або після завершення черги, навіть якщо в каналі є слухачі. Початок відтворення скасовує відлік. Поточний трек і черга зберігаються; після відновлення трек почнеться спочатку. Для порожнього каналу також діє окремий час на повернення.</p></fieldset>
    {editable && <div className="form-actions"><Button type="submit">Зберегти налаштування</Button></div>}
  </ActionForm></section>;
}
